---
- name: Listen for events on a webhook for S3
  hosts: all

  ## Define our source for events
  
  sources:
  - name: s3_events
    ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000

  rules:
  - name: process_uploaded_file
    condition: event.payload.detail.object.key is regex (".*\.csv", ignorecase=true)
    action:
      run_job_template:
        name: S3ProcessFile
        extra_vars:
          bucket_name: "{{ event.payload.detail.bucket.name }}"
          object_key: "{{ event.payload.detail.object.key }}"
        organization: Default
