---
- name: Listen for events on a webhook for S3
  hosts: all

  ## Define our source for events
  
  sources:
  - name: s3_events
    ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000

  rules:
  - name: process_uploaded_file
    condition: event.detail.object.key == "data.csv"
    action:
      run_job_template:
        name: ProcessFile
        organization: Default
