---
- name: Stop EC2 instances outside work hours
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: running_after_20h
      condition: event.payload.detail.state == 'running' and event.payload.time[11:13] >= "20"
      action:
        debug:
          msg: "Instance {{ event.payload.detail['instance-id'] }} doit être arrêtée"

    - name: running_before_6h
      condition: event.payload.detail.state == 'running' and event.payload.time[11:13] < "06"
      action:
        debug:
          msg: "Instance {{ event.payload.detail['instance-id'] }} doit être arrêtée"
