---
- name: Stop EC2 instances outside business hours
  hosts: localhost
  sources:
    - ansible.eda.webhook:  # connecté à l'EventBridge
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Stop dev EC2 instances
      condition: >
        {{event.payload.detail.state == "running"
        and (lookup('pipe', 'date +%H') | int >= 6 
          or lookup('pipe', 'date +%H') | int < 20)}}
      action:
        run_job_template:
          name: "Stop EC2 Dev Instance"
          organization: "Default"
          job_args:
            extra_vars:
              instance_id: "{{ event.payload.detail['instance-id'] }}"
