---
- name: Stop EC2 instances outside work hours
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  # Ici on calcule l'heure courante côté hôte local
  vars:
    hour: 22

  rules:
    - name: Stop dev EC2 instances outside 6h-20h
      condition: event.payload.detail.state == 'running' and (hour < 6 or hour >= 20)
      action:
        debug:
          msg: "Instance {{ event.payload.detail['instance-id'] }} doit être arrêtée"
