---
- name: Stop EC2 instances outside work hours
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Stop dev EC2 instances outside 6h-20h
      condition: event.payload.detail.state == 'running' and (now()[11:13] >= "20" or now()[11:13] < "06")
      action:
        debug:
          msg: "Instance {{ event.payload.detail['instance-id'] }} doit être arrêtée"
