---
- name: Stop EC2 instances outside work hours
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  # Ici on calcule l'heure courante côté hôte local
  vars:
    current_hour_cmd: "{{ lookup('pipe', 'date +%H') }}"
    hour: "{{ current_hour_cmd | int }}"

  rules:
    - name: Stop dev EC2 instances inside 6h-20h
      condition: event.payload.detail.state == 'running' and hour < 20 and hour >= 6
      action:
        debug:
          msg: "Instance {{ event.payload.detail['instance-id'] }} doit être arrêtée"
