---
- name: Process uploaded CSV file
  hosts: localhost
  gather_facts: false
  vars:
    bucket_name: "{{ event.payload.detail.bucket.name }}"
    object_key: "{{ event.payload.detail.object.key }}"
  tasks:
    - name: Download file from S3
      amazon.aws.aws_s3:
        bucket: "{{ bucket_name }}"
        object: "{{ object_key }}"
        dest: "/tmp/{{ object_key }}"
        mode: get

    - name: Validate CSV format
      ansible.builtin.command:
        cmd: "python3 /scripts/validate.py /tmp/{{ object_key }}"
        
    - name: Display system information
      debug:
        msg: "The file {{ object_key }} is in the {{ bucket_name }} bucket"
